param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [Parameter(Mandatory = $true)]
    [string]$RepoRoot
)

$owner = "free5all"
$name = "SimpleAudioRouter"

try {
    Push-Location $RepoRoot
    if (Get-Command git -ErrorAction SilentlyContinue) {
        $remote = git config --get remote.origin.url 2>$null
    }
}
finally {
    Pop-Location
}

if ($remote -match 'github\.com[/:](?<owner>[^/]+)/(?<name>[^/.]+?)(?:\.git)?/?$') {
    $owner = $Matches.owner
    $name = $Matches.name
}

$content = @"
// <auto-generated />
namespace SimpleAudioRouter;

internal static partial class RepositoryInfo
{
    public const string Owner = "$owner";
    public const string Name = "$name";
    public const string ReleasePageUrl = "https://github.com/$owner/$name/releases";
}
"@

$directory = Split-Path $OutputPath -Parent
if ($directory) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

[System.IO.File]::WriteAllText($OutputPath, $content + [Environment]::NewLine)
